package com.gk.bricks.util

enum class WiFiServerStatus {
                            CABIN_SEARCHING,CABIN_NOT_FOUND,CABIN_CONNECTING,CABIN_CONNECTED,CABIN_DIS_CONNECTING,
                            SERVER_CONNECTING,SERVER_NOT_FOUND,SERVER_CONNECTED,SERVER_DISCONNECTING,




    CONNECTED,ALREADY_CONNECTED,NOT_CONNECTED,CONNECTING,DISCONNECTING,NOT_REACHABLE,NONE;
}